FROM mcr.microsoft.com/dotnet/core/aspnet
ADD PublishOutput/ /inetpub/wwwroot

# add a certificate and configure SSL
SHELL ["powershell","-command"]
RUN New-Item -ItemType Directory C:\installsite
ADD installwebsite.ps1 c:\installsite\
ADD container.abcxdomain.com.pfx c:\installsite\
# Powershell script to configure SSL on the website
RUN c:\installsite\installwebsite

# plugin into SF healthcheck ensuring the container website is running
HEALTHCHECK --interval=30s --timeout=30s --start-period=60s --retries=3 CMD curl -f http://localhost/ || exit 1
